title: Paper Submission Deadlines
description: Countdowns to SE/ICT4S/AI conference/workshop deadlines
author: June Sallou

domain: "https://jnsll.github.io/deadlines/"
baseurl: "/deadlines"

twitter_hashtag: junesallou
github_username: Jnsll
github_repo: deadlines

markdown: kramdown
#ga_id:

include: ['_pages']
